version: '3.9'

services:
  front-end:
    container_name: app
    build: ./FrontEnd
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    depends_on:
      - back-end
    restart: always
    networks:
      - restaurant
  
  back-end:
    container_name: server
    build: ./BackEnd
    ports:
      - "3000:3000"
    depends_on:
      - database
    restart: always
    networks:
      - restaurant
  
  database:
    container_name: database
    build: ./Database
    restart: always
    networks:
      - restaurant
    volumes:
      - data:/var/lib

networks:
  restaurant: 
volumes:
  data: {}

